import { CalendarDays, MoreHorizontal, Pencil, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { Task } from '@/types'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { openTaskDrawer } from '@/store/uiSlice'
import { removeTask } from '@/store/taskSlice'
import { addActivity } from '@/store/collaborationSlice'
import { addNotification } from '@/store/notificationsSlice'
import Badge from '@/components/ui/Badge'
import Avatar from '@/components/ui/Avatar'
import Modal from '@/components/ui/Modal'
import ConfirmDialog from '@/components/ui/ConfirmDialog'
import TaskForm from './TaskForm'
import { formatLocalizedDate, useI18n } from '@/i18n'

const priorityColor={low:'#64748B',medium:'#3B82F6',high:'#F59E0B',critical:'#F43F5E'}
export default function TaskRow({task,mode='row'}:{task:Task;mode?:'row'|'card'}){
  const { language,t }=useI18n();const dispatch=useAppDispatch();const currentUser=useAppSelector((s)=>s.users.users.find((u)=>u.id===s.auth.currentUserId));const canEdit=currentUser?.role==='manager'||task.assigneeId===currentUser?.id;const canDelete=currentUser?.role==='manager';const user=useAppSelector((s)=>s.users.users.find((u)=>u.id===task.assigneeId));const column=useAppSelector((s)=>s.board.columns.find((c)=>c.id===task.columnId));const currentUserId=useAppSelector((s)=>s.auth.currentUserId)!;const[menu,setMenu]=useState(false);const[edit,setEdit]=useState(false);const[confirm,setConfirm]=useState(false)
  const remove=()=>{dispatch(removeTask(task.id));dispatch(addActivity({projectId:task.projectId,taskId:task.id,userId:currentUserId,type:'task-updated',message:`deleted ${task.title}`}));dispatch(addNotification({userId:currentUserId,title:'Task deleted',message:`${task.title} was deleted.`,type:'success',projectId:task.projectId}));setConfirm(false)}
  const confirmDescription=language==='fa'?`تسک «${task.title}» حذف شود؟ داده‌های محلی مرتبط با آن هم حذف می‌شوند.`:`Delete “${task.title}”? This also removes its local collaboration data.`
  if(mode==='card')return <div className="app-card p-4" onClick={()=>dispatch(openTaskDrawer(task.id))}><div className="flex items-start justify-between gap-2"><div><Badge color={priorityColor[task.priority]}>{t(task.priority)}</Badge><h3 className="mt-2 font-semibold">{task.title}</h3></div><button onClick={(e)=>{e.stopPropagation();setMenu((x)=>!x)}} className="btn btn-ghost min-h-10 w-10 p-0"><MoreHorizontal size={19}/></button></div>{menu&&<div className="mt-2 flex gap-3">{canEdit&&<button className="text-xs font-medium" onClick={(e)=>{e.stopPropagation();setEdit(true)}}>{t('Edit')}</button>}{canDelete&&<button className="text-xs font-medium text-red-500" onClick={(e)=>{e.stopPropagation();setConfirm(true)}}>{t('Delete')}</button>}</div>}<div className="mt-4 flex items-center justify-between text-xs" style={{color:'rgb(var(--muted))'}}><span>{column?t(column.title):t('Unknown')}</span><span className="flex items-center gap-1"><CalendarDays size={15}/>{formatLocalizedDate(task.dueDate,language)}</span></div>{user&&<div className="mt-3 flex items-center gap-2 text-xs"><Avatar name={user.name} src={user.avatar} size={26}/>{user.name}</div>}<Modal isOpen={edit} onClose={()=>setEdit(false)} title={t('Edit task')}><TaskForm projectId={task.projectId} task={task} onClose={()=>setEdit(false)}/></Modal><ConfirmDialog open={confirm} onClose={()=>setConfirm(false)} onConfirm={remove} title={t('Delete task')} description={confirmDescription}/></div>
  return <tr className="border-b hover:bg-[rgb(var(--surface-alt))]" style={{borderColor:'rgb(var(--border))'}}><td className="px-4 py-3"><button className="font-semibold hover:underline" onClick={()=>dispatch(openTaskDrawer(task.id))}>{task.title}</button></td><td className="px-4 py-3"><Badge color={column?.color}>{column?t(column.title):t('Unknown')}</Badge></td><td className="px-4 py-3"><Badge color={priorityColor[task.priority]}>{t(task.priority)}</Badge></td><td className="px-4 py-3">{user?<span className="flex items-center gap-2"><Avatar name={user.name} src={user.avatar} size={28}/>{user.name}</span>:'—'}</td><td className="px-4 py-3 text-sm">{formatLocalizedDate(task.dueDate,language)}</td><td className="px-4 py-3"><div className="flex gap-1">{canEdit&&<button className="btn btn-ghost min-h-10 w-10 p-0" onClick={()=>setEdit(true)} aria-label={t('Edit')}><Pencil size={18}/></button>}{canDelete&&<button className="btn btn-ghost min-h-10 w-10 p-0 text-red-500" onClick={()=>setConfirm(true)} aria-label={t('Delete')}><Trash2 size={18}/></button>}</div><Modal isOpen={edit} onClose={()=>setEdit(false)} title={t('Edit task')}><TaskForm projectId={task.projectId} task={task} onClose={()=>setEdit(false)}/></Modal><ConfirmDialog open={confirm} onClose={()=>setConfirm(false)} onConfirm={remove} title={t('Delete task')} description={confirmDescription}/></td></tr>
}
