import { RotateCcw, Search } from 'lucide-react'
import { useEffect } from 'react'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import Button from '@/components/ui/Button'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { resetFilters, setAssigneeFilter, setColumnFilter, setDueDateFrom, setDueDateTo, setPriority, setSearch, setSortBy, type PriorityFilter, type SortOption } from '@/store/taskFilterSlice'
import { useI18n } from '@/i18n'

export default function TaskFilters({ projectId }: { projectId: string }) {
  const { language, t }=useI18n();const dispatch=useAppDispatch();const filters=useAppSelector((s)=>s.taskFilter);const project=useAppSelector((s)=>s.project.projects.find((p)=>p.id===projectId));const users=useAppSelector((s)=>s.users.users.filter((u)=>project?.memberIds.includes(u.id)));const columns=useAppSelector((s)=>s.board.columns.filter((c)=>c.projectId===projectId).sort((a,b)=>a.order-b.order))
  useEffect(()=>{if(filters.columnId!=='all'&&!columns.some((c)=>c.id===filters.columnId))dispatch(setColumnFilter('all'));if(filters.assigneeId!=='all'&&!users.some((u)=>u.id===filters.assigneeId))dispatch(setAssigneeFilter('all'))},[projectId,filters.columnId,filters.assigneeId,columns,users,dispatch])
  return <div className="app-card mb-4 p-3"><div className="flex flex-col gap-3 xl:flex-row xl:items-end"><label className="min-w-52 flex-1"><span className="mb-1 block text-[11px] font-semibold">{t('Search')}</span><div className="relative"><Search className={`absolute top-1/2 -translate-y-1/2 ${language==='fa'?'right-3':'left-3'}`} size={18} style={{color:'rgb(var(--muted))'}}/><Input value={filters.search} onChange={(e)=>dispatch(setSearch(e.target.value))} placeholder={t('Search task title…')} className={language==='fa'?'pr-10':'pl-10'}/></div></label><label><span className="mb-1 block text-[11px] font-semibold">{t('Priority')}</span><Select value={filters.priority} onChange={(e)=>dispatch(setPriority(e.target.value as PriorityFilter))}><option value="all">{t('All priorities')}</option><option value="critical">{t('Critical')}</option><option value="high">{t('High')}</option><option value="medium">{t('Medium')}</option><option value="low">{t('Low')}</option></Select></label><label><span className="mb-1 block text-[11px] font-semibold">{t('Status')}</span><Select value={filters.columnId} onChange={(e)=>dispatch(setColumnFilter(e.target.value))}><option value="all">{t('All statuses')}</option>{columns.map((c)=><option key={c.id} value={c.id}>{t(c.title)}</option>)}</Select></label><label><span className="mb-1 block text-[11px] font-semibold">{t('Assignee')}</span><Select value={filters.assigneeId} onChange={(e)=>dispatch(setAssigneeFilter(e.target.value))}><option value="all">{t('All members')}</option>{users.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><label><span className="mb-1 block text-[11px] font-semibold">{t('From')}</span><Input type="date" value={filters.dueDateFrom} onChange={(e)=>dispatch(setDueDateFrom(e.target.value))}/></label><label><span className="mb-1 block text-[11px] font-semibold">{t('To')}</span><Input type="date" value={filters.dueDateTo} onChange={(e)=>dispatch(setDueDateTo(e.target.value))}/></label><label><span className="mb-1 block text-[11px] font-semibold">{t('Sort')}</span><Select value={filters.sortBy} onChange={(e)=>dispatch(setSortBy(e.target.value as SortOption))}><option value="none">{t('Default')}</option><option value="dueDateAsc">{t('Due soonest')}</option><option value="dueDateDesc">{t('Due latest')}</option><option value="priority">{t('Priority')}</option><option value="title">{t('Title')}</option></Select></label><Button variant="ghost" title={t('Reset filters')} onClick={()=>dispatch(resetFilters())}><RotateCcw size={19}/></Button></div></div>
}
