import { useState } from 'react'
import { Check, Flag, Plus, Tag } from 'lucide-react'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { addLabel, addMilestone, toggleMilestone } from '@/store/collaborationSlice'
import Input from '@/components/ui/Input'
import Button from '@/components/ui/Button'
import Badge from '@/components/ui/Badge'
import { useI18n } from '@/i18n'

export default function ProjectTools({projectId}:{projectId:string}){
  const { language,t }=useI18n();const dispatch=useAppDispatch();const currentUserId=useAppSelector((s)=>s.auth.currentUserId);const canManage=useAppSelector((s)=>s.users.users.find((u)=>u.id===currentUserId)?.role==='manager');const labels=useAppSelector((s)=>s.collaboration.labels.filter((l)=>l.projectId===projectId));const milestones=useAppSelector((s)=>s.collaboration.milestones.filter((m)=>m.projectId===projectId).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)));const[labelName,setLabelName]=useState('');const[labelColor,setLabelColor]=useState('#7C6CFF');const[milestoneTitle,setMilestoneTitle]=useState('');const[milestoneDate,setMilestoneDate]=useState('')
  return <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="app-card p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><Tag size={18}/>{t('Project labels')}</h3><div className="mb-3 flex flex-wrap gap-2">{labels.map((l)=><Badge key={l.id} color={l.color}>{l.name}</Badge>)}{!labels.length&&<span className="text-xs" style={{color:'rgb(var(--muted))'}}>{t('No labels yet.')}</span>}</div>{canManage&&<div className="flex gap-2"><Input value={labelName} onChange={(e)=>setLabelName(e.target.value)} placeholder={t('Label name')}/><input type="color" value={labelColor} onChange={(e)=>setLabelColor(e.target.value)} className="h-[44px] w-12 rounded-xl border p-1" style={{borderColor:'rgb(var(--border))'}}/><Button variant="secondary" onClick={()=>{if(labelName.trim()){dispatch(addLabel({projectId,name:labelName.trim(),color:labelColor}));setLabelName('')}}}><Plus size={18}/></Button></div>}</section><section className="app-card p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><Flag size={18}/>{t('Milestones')}</h3><div className="mb-3 space-y-2">{milestones.map((m)=><button key={m.id} disabled={!canManage} onClick={()=>dispatch(toggleMilestone(m.id))} className={`flex w-full items-center gap-2 rounded-xl bg-[rgb(var(--surface-alt))] p-2.5 ${language==='fa'?'text-right':'text-left'}`}><span className="flex h-6 w-6 items-center justify-center rounded-full border" style={{background:m.completed?'rgb(var(--success))':'transparent',borderColor:m.completed?'rgb(var(--success))':'rgb(var(--border))',color:'white'}}>{m.completed&&<Check size={14}/>}</span><span className={m.completed?'line-through opacity-60':''}>{m.title}</span><span className="ms-auto text-[10px]" style={{color:'rgb(var(--muted))'}}>{m.dueDate}</span></button>)}</div>{canManage&&<div className="grid gap-2 sm:grid-cols-[1fr_150px_auto]"><Input value={milestoneTitle} onChange={(e)=>setMilestoneTitle(e.target.value)} placeholder={t('Milestone title')}/><Input type="date" value={milestoneDate} onChange={(e)=>setMilestoneDate(e.target.value)}/><Button variant="secondary" onClick={()=>{if(milestoneTitle.trim()&&milestoneDate){dispatch(addMilestone({projectId,title:milestoneTitle.trim(),dueDate:milestoneDate}));setMilestoneTitle('');setMilestoneDate('')}}}><Plus size={18}/></Button></div>}</section></div>
}
