import { Archive, CalendarDays, Star } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import type { Project } from '@/types'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { toggleArchive, toggleFavorite } from '@/store/projectSlice'
import Progress from '@/components/ui/Progress'
import ProjectIcon from './ProjectIcon'
import Avatar from '@/components/ui/Avatar'
import { calcProjectProgress } from '@/utils/project'
import { formatLocalizedDate, useI18n } from '@/i18n'

export default function ProjectCard({ project }: { project: Project }) {
  const { language,t }=useI18n();const dispatch=useAppDispatch();const navigate=useNavigate();const currentUserId=useAppSelector((s)=>s.auth.currentUserId);const canManage=useAppSelector((s)=>s.users.users.find((u)=>u.id===currentUserId)?.role==='manager');const tasks=useAppSelector((s)=>s.task.tasks.filter((task)=>task.projectId===project.id&&!task.isArchived));const columns=useAppSelector((s)=>s.board.columns.filter((column)=>column.projectId===project.id));const users=useAppSelector((s)=>s.users.users.filter((u)=>project.memberIds.includes(u.id)));const progress=calcProjectProgress(tasks,columns)
  return <article className="app-card app-card-interactive group cursor-pointer overflow-hidden" onClick={()=>navigate(`/projects/${project.id}/board`)}><div className="h-1.5" style={{background:project.color}}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl" style={{background:`${project.color}18`,color:project.color}}><ProjectIcon iconKey={project.icon} size={19}/></span><h3 className="truncate text-lg font-semibold">{project.title}</h3></div><p className="mt-1 line-clamp-2 min-h-10 text-sm" style={{color:'rgb(var(--text-secondary))'}}>{project.description}</p></div><div className="flex shrink-0 gap-1"><button className="btn btn-ghost min-h-10 w-10 p-0" onClick={(e)=>{e.stopPropagation();dispatch(toggleFavorite(project.id))}} aria-label={t('Favorite')}><Star size={19} fill={project.isFavorite?'currentColor':'none'} style={{color:project.isFavorite?'#F59E0B':undefined}}/></button>{canManage&&<button className="btn btn-ghost min-h-10 w-10 p-0" onClick={(e)=>{e.stopPropagation();dispatch(toggleArchive(project.id))}} title={t('Archive')}><Archive size={18}/></button>}</div></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span>{t('Progress')}</span><strong>{progress}%</strong></div><Progress value={progress} color={project.color}/></div><div className="mt-5 flex items-center justify-between"><div className="flex -space-x-2 rtl:space-x-reverse">{users.slice(0,4).map((u)=><span key={u.id} className="rounded-full ring-2 ring-[rgb(var(--surface))]"><Avatar name={u.name} src={u.avatar} size={30}/></span>)}{users.length>4&&<span className="flex h-[30px] w-[30px] items-center justify-center rounded-full bg-[rgb(var(--surface-alt))] text-[10px] ring-2 ring-[rgb(var(--surface))]">+{users.length-4}</span>}</div><div className="flex items-center gap-1.5 text-xs" style={{color:'rgb(var(--muted))'}}><CalendarDays size={16}/>{formatLocalizedDate(project.dueDate,language)}</div></div></div></article>
}
