import { useState } from 'react'
import { Plus, Trash2, Zap } from 'lucide-react'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { addAutomationRule, removeAutomationRule, toggleAutomationRule } from '@/store/automationSlice'
import type { AutomationAction, AutomationTrigger } from '@/types'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import Modal from '@/components/ui/Modal'
import Switch from '@/components/ui/Switch'
import { useI18n } from '@/i18n'

const triggerLabel: Record<AutomationTrigger,string> = { due_tomorrow:'Task due tomorrow', task_completed:'Task completed', high_priority_created:'High-priority task created' }
const actionLabel: Record<AutomationAction,string> = { notify_assignee:'Notify assignee', notify_manager:'Notify manager' }

export default function AutomationsPage(){
  const { t }=useI18n();const dispatch=useAppDispatch();const currentUserId=useAppSelector((s)=>s.auth.currentUserId);const canManage=useAppSelector((s)=>s.users.users.find((u)=>u.id===currentUserId)?.role==='manager');const rules=useAppSelector((s)=>s.automation.rules);const projects=useAppSelector((s)=>s.project.projects.filter((p)=>!p.isArchived));const[open,setOpen]=useState(false);const[name,setName]=useState('');const[trigger,setTrigger]=useState<AutomationTrigger>('due_tomorrow');const[action,setAction]=useState<AutomationAction>('notify_assignee');const[projectId,setProjectId]=useState('')
  const add=()=>{if(!name.trim())return;dispatch(addAutomationRule({name:name.trim(),trigger,action,projectId:projectId||undefined}));setOpen(false);setName('')}
  return <div className="page-container"><div className="mb-6 flex items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.18em]" style={{color:'rgb(var(--primary))'}}>{t('Rules')}</div><h1 className="mt-1 text-3xl font-bold">{t('Automations')}</h1><p className="mt-2" style={{color:'rgb(var(--muted))'}}>{t('Simple trigger → action rules, inspired by Trello Butler and Asana Rules.')}</p></div>{canManage&&<Button icon={Plus} onClick={()=>setOpen(true)}>{t('New rule')}</Button>}</div><div className="grid gap-4 lg:grid-cols-2">{rules.map((rule)=><article key={rule.id} className="app-card p-5"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl" style={{background:'rgb(var(--primary-soft))',color:'rgb(var(--primary))'}}><Zap size={20}/></span><div className="min-w-0 flex-1"><h3 className="font-semibold">{rule.name}</h3><p className="mt-1 text-xs" style={{color:'rgb(var(--muted))'}}>{t('WHEN')} <strong>{t(triggerLabel[rule.trigger])}</strong> → {t('THEN')} <strong>{t(actionLabel[rule.action])}</strong></p></div><Switch disabled={!canManage} checked={rule.enabled} onChange={()=>dispatch(toggleAutomationRule(rule.id))}/>{canManage&&<button className="btn btn-ghost min-h-10 w-10 p-0 text-red-500" onClick={()=>dispatch(removeAutomationRule(rule.id))}><Trash2 size={18}/></button>}</div></article>)}</div><Modal isOpen={open} onClose={()=>setOpen(false)} title={t('Create automation')}><div className="space-y-4"><label><span className="mb-1 block text-xs font-semibold">{t('Rule name')}</span><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder={t('Notify me about urgent work')}/></label><label><span className="mb-1 block text-xs font-semibold">{t('Project (optional)')}</span><Select value={projectId} onChange={(e)=>setProjectId(e.target.value)}><option value="">{t('All projects')}</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.title}</option>)}</Select></label><label><span className="mb-1 block text-xs font-semibold">{t('Trigger')}</span><Select value={trigger} onChange={(e)=>setTrigger(e.target.value as AutomationTrigger)}><option value="due_tomorrow">{t('Task due tomorrow')}</option><option value="task_completed">{t('Task completed')}</option><option value="high_priority_created">{t('High-priority task created')}</option></Select></label><label><span className="mb-1 block text-xs font-semibold">{t('Action')}</span><Select value={action} onChange={(e)=>setAction(e.target.value as AutomationAction)}><option value="notify_assignee">{t('Notify assignee')}</option><option value="notify_manager">{t('Notify manager')}</option></Select></label><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setOpen(false)}>{t('Cancel')}</Button><Button onClick={add}>{t('Create rule')}</Button></div></div></Modal></div>
}
