import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, Languages } from 'lucide-react'
import Input from '@/components/ui/Input'
import Button from '@/components/ui/Button'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { setCurrentUser } from '@/store/authSlice'
import { hashPassword } from '@/utils/password'
import { useI18n } from '@/i18n'

export default function LoginPage() {
  const { language, t, toggleLanguage } = useI18n()
  const dispatch = useAppDispatch(); const navigate = useNavigate(); const location = useLocation(); const users = useAppSelector((s)=>s.users.users)
  const [email,setEmail]=useState('manager@aurora.local'); const [password,setPassword]=useState('123456'); const [show,setShow]=useState(false); const [remember,setRemember]=useState(true); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(''); const hash=await hashPassword(password); const user=users.find((u)=>u.email.toLowerCase()===email.trim().toLowerCase()&&u.passwordHash===hash&&u.isActive); if(!user){setError(t('Email or password is incorrect.'));setLoading(false);return} dispatch(setCurrentUser({userId:user.id,rememberMe:remember})); const from=(location.state as {from?:string}|null)?.from ?? '/dashboard'; navigate(from,{replace:true}) }
  return <div className="relative grid min-h-screen lg:grid-cols-2">
    <button onClick={toggleLanguage} className="btn btn-secondary icon-action absolute top-5 z-20" style={{ [language==='fa'?'left':'right']: '20px' }} aria-label={t('Change language')} title={language==='en'?'فارسی':'English'}><Languages size={21}/></button>
    <div className="relative hidden overflow-hidden p-12 text-white lg:flex lg:flex-col lg:justify-between" style={{background:'radial-gradient(circle at 20% 15%,#8B5CF6 0,#635BFF 35%,#111827 100%)'}}><div className="absolute inset-0 opacity-40" style={{backgroundImage:'radial-gradient(circle,rgba(255,255,255,.72) 0 1px,transparent 1.4px)',backgroundSize:'86px 86px'}}/><div className="relative flex items-center gap-3 text-xl font-bold"><span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-white/15 bg-[#17162d]/70 shadow-xl"><img src="/athena-logo.png" alt="" className="h-11 w-11 object-contain"/></span>Athena Workspace</div><div className="relative max-w-lg"><h1 className="text-5xl font-bold leading-tight">{t('Plan clearly. Move faster. Build together.')}</h1><p className="mt-5 text-lg text-white/70">{t('A premium frontend-only team workspace inspired by the best parts of Trello and Asana.')}</p></div><div className="relative text-sm text-white/50">React · TypeScript · Redux Toolkit · LocalStorage</div></div>
    <div className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-md"><div className="mb-8"><div className="mb-2 text-sm font-semibold" style={{color:'rgb(var(--primary))'}}>{t('WELCOME BACK')}</div><h2 className="text-3xl font-bold">{t('Sign in to Athena')}</h2><p className="mt-2" style={{color:'rgb(var(--muted))'}}>{t('Continue to your team workspace.')}</p></div><div className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-semibold">{t('Email')}</span><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">{t('Password')}</span><div className="relative"><Input type={show?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} required className={language==='fa'?'pl-12':'pr-12'}/><button type="button" className={`absolute top-1/2 -translate-y-1/2 ${language==='fa'?'left-3':'right-3'}`} onClick={()=>setShow((x)=>!x)} aria-label={t(show?'Hide password':'Show password')}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)}/><span>{t('Keep me signed in')}</span></label>{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}<Button className="w-full" type="submit" disabled={loading}>{loading?t('Signing in…'):t('Sign in')}</Button></div><div className="mt-6 app-card p-4 text-xs"><strong>{t('Demo account')}</strong><div className="mt-2" dir="ltr" style={{color:'rgb(var(--text-secondary))'}}>manager@aurora.local / 123456</div></div><p className="mt-6 text-center text-sm" style={{color:'rgb(var(--muted))'}}>{t('No account?')} <Link className="font-semibold" style={{color:'rgb(var(--primary))'}} to="/register">{t('Create one')}</Link></p></form></div>
  </div>
}
