import { useMemo, useState } from 'react'
import { useAppSelector } from '@/store/hooks'
import TaskRow from '@/components/task/TaskRow'
import EmptyState from '@/components/ui/EmptyState'
import { daysUntil } from '@/utils/date'
import { useI18n } from '@/i18n'

type Tab='today'|'upcoming'|'overdue'|'completed'
const tabLabels:Record<Tab,string>={today:'Today',upcoming:'Upcoming',overdue:'Overdue',completed:'Completed'}
const emptyLabels:Record<Tab,string>={today:'No today tasks',upcoming:'No upcoming tasks',overdue:'No overdue tasks',completed:'No completed tasks'}
export default function MyTasksPage(){
  const { language,t }=useI18n();const userId=useAppSelector((s)=>s.auth.currentUserId);const tasks=useAppSelector((s)=>s.task.tasks.filter((task)=>task.assigneeId===userId&&!task.isArchived));const completedIds=new Set(useAppSelector((s)=>s.board.columns.filter((column)=>column.isCompletedColumn).map((column)=>column.id)));const[tab,setTab]=useState<Tab>('today')
  const items=useMemo(()=>tasks.filter((task)=>{const done=completedIds.has(task.columnId),days=daysUntil(task.dueDate);if(tab==='completed')return done;if(done)return false;if(tab==='today')return days===0;if(tab==='upcoming')return days>0;if(tab==='overdue')return days<0;return true}).sort((a,b)=>(a.dueDate??'').localeCompare(b.dueDate??'')),[tasks,tab,completedIds])
  const counts={today:tasks.filter((task)=>!completedIds.has(task.columnId)&&daysUntil(task.dueDate)===0).length,upcoming:tasks.filter((task)=>!completedIds.has(task.columnId)&&daysUntil(task.dueDate)>0).length,overdue:tasks.filter((task)=>!completedIds.has(task.columnId)&&daysUntil(task.dueDate)<0).length,completed:tasks.filter((task)=>completedIds.has(task.columnId)).length}
  return <div className="page-container"><div className="mb-6"><div className="text-xs font-bold uppercase tracking-[.18em]" style={{color:'rgb(var(--primary))'}}>{t('Focus')}</div><h1 className="mt-1 text-3xl font-bold">{t('My Tasks')}</h1><p className="mt-2" style={{color:'rgb(var(--muted))'}}>{t('Everything assigned to you, organized by urgency.')}</p></div><div className="mb-5 flex gap-2 overflow-x-auto">{(['today','upcoming','overdue','completed'] as Tab[]).map((item)=><button key={item} onClick={()=>setTab(item)} className={`shrink-0 rounded-xl px-4 py-2 text-sm font-semibold ${tab===item?'text-white':''}`} style={tab===item?{background:'linear-gradient(135deg,rgb(var(--primary)),rgb(var(--info)))'}:{background:'rgb(var(--surface-alt))'}}>{t(tabLabels[item])} <span className={language==='fa'?'mr-1 opacity-70':'ml-1 opacity-70'}>{counts[item]}</span></button>)}</div>{items.length?<div className="space-y-3 md:hidden">{items.map((task)=><TaskRow key={task.id} task={task} mode="card"/>)}</div>:<EmptyState title={t(emptyLabels[tab])} description={t('Nothing needs your attention in this section.')}/>}<div className="app-card hidden overflow-hidden md:block"><table className={`w-full text-sm ${language==='fa'?'text-right':'text-left'}`}><thead className="bg-[rgb(var(--surface-alt))] text-xs"><tr><th className="px-4 py-3">{t('Task')}</th><th className="px-4 py-3">{t('Status')}</th><th className="px-4 py-3">{t('Priority')}</th><th className="px-4 py-3">{t('Assignee')}</th><th className="px-4 py-3">{t('Due')}</th><th className="px-4 py-3">{t('Actions')}</th></tr></thead><tbody>{items.map((task)=><TaskRow key={task.id} task={task}/>)}</tbody></table></div></div>
}
