import { useNavigate, useParams } from 'react-router-dom'
import { useAppSelector } from '@/store/hooks'
import { useI18n } from '@/i18n'
import ProjectForm from '@/components/project/ProjectForm'
import TaskForm from '@/components/task/TaskForm'

function AccessDenied() {
  const { t } = useI18n()
  return <div className="page-container"><div className="app-card mx-auto max-w-xl p-8 text-center"><h1 className="text-xl font-bold">{t('Access denied')}</h1><p className="mt-2 text-sm" style={{ color: 'rgb(var(--muted))' }}>{t('Your current role cannot edit this resource.')}</p></div></div>
}
export function ProjectCreatePage() { const { t }=useI18n(); const navigate=useNavigate(); const userId=useAppSelector((s)=>s.auth.currentUserId); const isManager=useAppSelector((s)=>s.users.users.find((u)=>u.id===userId)?.role==='manager'); if(!isManager)return <AccessDenied/>; return <div className="page-container"><div className="app-card mx-auto max-w-2xl p-6"><h1 className="mb-5 text-2xl font-bold">{t('Create project')}</h1><ProjectForm onClose={()=>navigate('/projects')}/></div></div> }
export function ProjectEditPage() { const { t }=useI18n(); const navigate=useNavigate(); const {projectId=''}=useParams(); const userId=useAppSelector((s)=>s.auth.currentUserId); const isManager=useAppSelector((s)=>s.users.users.find((u)=>u.id===userId)?.role==='manager'); const project=useAppSelector((s)=>s.project.projects.find((p)=>p.id===projectId)); if(!isManager)return <AccessDenied/>; if(!project)return <div className="page-container">{t('Project not found.')}</div>; return <div className="page-container"><div className="app-card mx-auto max-w-2xl p-6"><h1 className="mb-5 text-2xl font-bold">{t('Edit project')}</h1><ProjectForm project={project} onClose={()=>navigate(`/projects/${projectId}/board`)}/></div></div> }
export function TaskCreatePage() { const { t }=useI18n(); const navigate=useNavigate(); const {projectId=''}=useParams(); const userId=useAppSelector((s)=>s.auth.currentUserId); const isManager=useAppSelector((s)=>s.users.users.find((u)=>u.id===userId)?.role==='manager'); if(!isManager)return <AccessDenied/>; return <div className="page-container"><div className="app-card mx-auto max-w-2xl p-6"><h1 className="mb-5 text-2xl font-bold">{t('Create task')}</h1><TaskForm projectId={projectId} onClose={()=>navigate(`/projects/${projectId}/list`)}/></div></div> }
export function TaskEditPage() { const { t }=useI18n(); const navigate=useNavigate(); const {projectId='',taskId=''}=useParams(); const userId=useAppSelector((s)=>s.auth.currentUserId); const user=useAppSelector((s)=>s.users.users.find((u)=>u.id===userId)); const task=useAppSelector((s)=>s.task.tasks.find((item)=>item.id===taskId&&item.projectId===projectId)); if(!task)return <div className="page-container">{t('Task not found.')}</div>; if(user?.role!=='manager'&&task.assigneeId!==userId)return <AccessDenied/>; return <div className="page-container"><div className="app-card mx-auto max-w-2xl p-6"><h1 className="mb-5 text-2xl font-bold">{t('Edit task')}</h1><TaskForm projectId={projectId} task={task} onClose={()=>navigate(`/projects/${projectId}/list`)}/></div></div> }
