import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, Languages } from 'lucide-react'
import Input from '@/components/ui/Input'
import Button from '@/components/ui/Button'
import { useAppDispatch, useAppSelector } from '@/store/hooks'
import { addUser } from '@/store/usersSlice'
import { setCurrentUser } from '@/store/authSlice'
import { hashPassword } from '@/utils/password'
import { useI18n } from '@/i18n'

export default function RegisterPage(){
  const { language,t,toggleLanguage }=useI18n();const dispatch=useAppDispatch();const navigate=useNavigate();const users=useAppSelector((s)=>s.users.users);const[name,setName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password.length<6){setError(t('Password must be at least 6 characters.'));return}if(users.some((u)=>u.email.toLowerCase()===email.trim().toLowerCase())){setError(t('An account with this email already exists.'));return}const passwordHash=await hashPassword(password);const action=dispatch(addUser({name,email,passwordHash,role:'member'}));dispatch(setCurrentUser({userId:action.payload.id,rememberMe:true}));navigate('/dashboard')}
  return <div className="relative flex min-h-screen items-center justify-center p-6"><button onClick={toggleLanguage} className="btn btn-secondary icon-action absolute top-5" style={{[language==='fa'?'left':'right']:'20px'}} aria-label={t('Change language')} title={language==='en'?'فارسی':'English'}><Languages size={21}/></button><form onSubmit={submit} className="app-card w-full max-w-lg p-6 md:p-8"><div className="mb-6"><div className="text-sm font-semibold" style={{color:'rgb(var(--primary))'}}>{t('CREATE ACCOUNT')}</div><h1 className="mt-2 text-3xl font-bold">{t('Join your workspace')}</h1><p className="mt-2" style={{color:'rgb(var(--muted))'}}>{t('Local authentication for this frontend-only project.')}</p></div><div className="space-y-4"><label className="block"><span className="mb-1 block text-xs font-semibold">{t('Name')}</span><Input value={name} onChange={(e)=>setName(e.target.value)} required/></label><label className="block"><span className="mb-1 block text-xs font-semibold">{t('Email')}</span><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></label><label className="block"><span className="mb-1 block text-xs font-semibold">{t('Password')}</span><div className="relative"><Input type={showPassword?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} required className={language==='fa'?'pl-12':'pr-12'}/><button type="button" aria-label={t(showPassword?'Hide password':'Show password')} className={`absolute top-1/2 -translate-y-1/2 ${language==='fa'?'left-3':'right-3'}`} onClick={()=>setShowPassword((value)=>!value)}>{showPassword?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label>{error&&<div className="rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}<Button className="w-full">{t('Create account')}</Button></div><p className="mt-6 text-center text-sm" style={{color:'rgb(var(--muted))'}}>{t('Already registered?')} <Link to="/login" className="font-semibold" style={{color:'rgb(var(--primary))'}}>{t('Sign in')}</Link></p></form></div>
}
